Created the Entity for the Review table
ucsb-cs156-f24/proj-dining-f24-16 pull request #34
Opened 2024-11-15 02:15 UTC by jayster7101

Closes #6 

The entity for the review table is implemented.

2024-11-19 23:58 UTC, li-kelly submitted a review, later dismissed
LGTM

2024-11-22 01:03 UTC, rohanpreetam submitted a review, later dismissed
LGTM

2024-11-22 19:31 UTC, li-kelly submitted a review, later dismissed
LGTM

2024-11-23 20:05 UTC, pconrad requested changes
We normally include the repository file and the database migration file in the same PR.   I'll look for these; typically you only earn 5 points for adding all three in one PR.

Do you have these in a later PR?

2024-11-24 22:50 UTC, jayster7101 commented on src/main/java/edu/ucsb/cs156/dining/entities/Review.java
> +    private LocalDateTime dateEdited;
I tried this, followed all steps and tried debugging for 2 hours. 
I narrowed it down to one of these, I cant remember which statement exactly did it:
@EntityListeners(AuditingEntityListener.class) ~ I think it was this 
@EnableJpaAuditing(dateTimeProviderRef = "utcDateTimeProvider")

But it would brick the whole app. I did follow all the directions and had the functions defined as stated in the article/post. 

I went with the current implementation or setting it manually.

2024-11-25 00:43 UTC, pconrad approved these changes
LGTM

2024-11-25 00:43 UTC, merged