Claire feat2 back
ucsb-cs156-f24/proj-dining-f24-16 pull request #51
Opened 2024-11-22 01:34 UTC by cs11111111

2024-11-22 19:34 UTC, li-kelly submitted a review, later dismissed
LGTM, I'm able to change my alias on the dokku and I can change my moderation value also because I'm an admin.

2024-11-23 20:44 UTC, pconrad requested changes
The controller code here is in the wrong controller. Should go in `UsersController`.

2024-11-23 20:44 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UserInfoController.java
> +    }
Same with this method:

I think this should go in the [`UsersController.java`](https://github.com/ucsb-cs156-f24/proj-dining-f24-16/blob/main/src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java) not the UserInfoController.

UserInfoController has a different purpose in the application.  

Please relocate this code to where future developers will be expecting to find it.

2024-11-23 20:44 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UserInfoController.java
> +    }
I think this should go in the [`UsersController.java`](https://github.com/ucsb-cs156-f24/proj-dining-f24-16/blob/main/src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java) not the UserInfoController.

UserInfoController has a different purpose in the application.  

Please relocate this code to where future developers will be expecting to find it.

2024-11-23 20:44 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/entities/User.java
> +  private Boolean moderation;
The normal naming convention here would be `moderator` (to match) `admin`.

2024-11-23 20:44 UTC, pconrad commented on src/main/resources/db/migration/changes/Users.json
> +                    "name": "MODERATION",
```suggestion
                    "name": "MODERATOR",
```

2024-11-23 20:44 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/entities/User.java
> +  private Boolean moderation;
```suggestion
  private Boolean moderator;
```

2024-11-25 01:02 UTC, pconrad requested changes
Some changes needed in this one.

2024-11-25 01:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java
> +    }
This implementation going to be very confusing, because the `moderator` field looks like a field that would be used to determine whether or not someone has the role `moderator`.  But you are using it for a field to indicate whether an alias has been approved or not—and it actually doesn't hold enough information for that.   

I'd suggest getting rid of the moderator field UNLESS you are using it in the same way that the `admin` field is being used, to indicate a role.  If you want to keep a boolean field to indicate whether the alias is approved or not, name it something else, such as aliasApproved.   But I don't think you need that. I think you can use:

*  `proposedAlias==null` to mean that the users `alias` field is in effect
* `proposedAlias!=null` to mean that the user has requested a new alias and the moderator needs to review it.

When a moderator approves a `proposedAlias` the controller copies `proposedAlias` into `alias`, and sets `proposedAlias` to null.

When a moderator rejects a proposedAlias, the controller just sets proposedAlias to null.

The user should be able to update proposedAlias only.

2024-11-25 01:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java
> +        user.setAlias(alias);
WAIT... no, the user can't just update their own alias.  They have to update the "proposed" alias, and then a moderator has to "approve" the new alias.

You need a field for the actual alias (which starts out as "Anonymous User") and then a field for the proposed new alias (proposedAlias).  The user can only update the "proposedAlias" field.   When the moderator approves the new alias, then and only then, it gets copied into the alias field, and the proposedAlias field gets set back to null.

You also need a controller method for admins that will return a list of all users where the proposedAlias is not null; that's would be used for a page where the admin can review proposed aliases and either approve or deny them.

2024-11-25 01:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java
> +        user.setAlias(alias);
```suggestion
        user.setProposedAlias(proposedAlias)
```

2024-11-25 01:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java
> +    public User updateAlias(@RequestParam String alias) {
```suggestion
    public User updateAlias(@RequestParam String proposedAlias) {
```

2024-11-25 01:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java
> +    @Operation(summary = "Update alias of the current user")
```suggestion
    @Operation(summary = "Update proposedAlias of the current user")
```

2024-11-25 01:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java
> +        user.setAlias(alias);
You also need to do one more thing: check whether the proposedAlias overlaps with any current alias, or proposedAlias.  We really want these to be unique, even if users change them from time to time.

2024-11-25 01:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java
> +        user.setAlias(alias);
So that means a database look up by alias, and one by proposedAlias, which you can add to the UserRepository.

2024-11-26 03:23 UTC, pconrad approved these changes
LGTM... will test on dokku

2024-11-26 03:25 UTC, merged