Review controller post and get all
ucsb-cs156-f24/proj-dining-f24-16 pull request #52
Opened 2024-11-22 02:04 UTC by jayster7101

This PR accomplishes the following: 
1) It is built on top of the Entity from issue #34 
2) implements two methods:
- An _Admin_ get all method that takes in no argument and returns all reviews regardless of their status
- A _User_ post method that is used to create a review given the following params: the **ItemId** (which is a string) and the **date**/time the item was served (a LocalDateTime type). 

**Testing:**
The test file: ReviewControllerTests.java
- has 100% line coverage on the unit test
- has 100% mutation testing for the 

Tests:
- checking to see if logged-out user can get all the reviews
- checking to see if logged-out user can post a new review
- checking to see if logged-in Admin can get all the reviews
- checking to see if logged-in User can get all the reviews
- Ensures that a logged in user can in fact post a review 
- Ensures that the data the Admin requests from getting all works as expected

Checking endpoints:
To validate this, please the use swagger endpoint on this dokku instance:
https://proj-dining-dev-jayster7101.dokku-16.cs.ucsb.edu/

2024-11-23 20:53 UTC, pconrad requested changes
A couple of crucial missing pieces: the number of stars and the actual review comments.  

Without those, there is literally no point in building the application, and definitely no point in the moderation features (what are the moderators even moderating, if not the review comments? )

2024-11-23 20:53 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +     *                       set to be null or some other signifier
I agree that most of the other items are set from data sources that are determined in other ways (e.g. current date, current user id), but what about the number of stars and the review comment?  

Without those, what is even the point of posting a review?

I think you need to add those!

2024-11-23 20:53 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +        review.setDateCreated(now);
Consider doing this automatically using the techniques described here:

https://ucsb-cs156.github.io/topics/spring_boot/spring_boot_database.html#timestamps-on-database-rows

2024-11-23 20:53 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +        review.setItemId(itemId);
You need to look up the itemId in the MenuItems table (which needs to exist before this PR can be merged).  And if that itemId doesn't exist in the MenuItems table, you need to throw an exception.

Similar to this code:
https://github.com/ucsb-cs156/proj-courses/blob/4bdc2674508428d03cb2dcd2e9077d75cdaf5a3f/src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java#L114

2024-11-23 20:53 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +        review.setStudentId(user.getUser().getId());
Good!  Nicely done.

2024-11-23 20:53 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +        review.setDateEdited(now);
Consider using https://ucsb-cs156.github.io/topics/spring_boot/spring_boot_database.html#timestamps-on-database-rows instead.

2024-11-23 20:53 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/entities/Review.java
> +    private LocalDateTime dateEdited;
Consider using https://ucsb-cs156.github.io/topics/spring_boot/spring_boot_database.html#timestamps-on-database-rows

2024-11-23 20:53 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/entities/Review.java
> +
Where is the column for number of stars and the user's review comments?

Those are kind of the *whole point* of the application, so I think we need those.  We are building a minimum *viable* product, and without those, we don't have a *viable* product.

2024-11-25 01:30 UTC, jayster7101 commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +     *                       set to be null or some other signifier
added those now.

2024-11-25 01:31 UTC, jayster7101 commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +        review.setDateCreated(now);
Left a comment in an earlier pr how i was unable to implement as of now. Will revisit and refactor if given time but currently works

2024-11-25 01:32 UTC, jayster7101 commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +        review.setStudentId(user.getUser().getId());
thank you :)

2024-11-25 23:15 UTC, cs11111111 approved these changes
LGTM. I can input and get reviews logged in, but can not when logged out.

2024-11-26 03:27 UTC, pconrad approved these changes
LGTM!  Nice work

2024-11-26 03:27 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +     *                       set to be null or some other signifier
Strictly speaking, you should add those to the javadoc comment as well, but I'll let that go since it's late in the process.

2024-11-26 03:27 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
> +            throw new IllegalArgumentException("Items stars must be between 1 and 5.");
nice!

2024-11-26 22:26 UTC, pconrad approved these changes
LGTM

2024-11-26 22:50 UTC, merged